### ISSUE TITLE
Large generated files committed to git

### ISSUE THREAD

**Issue by traviscross** [Kobzol/cargo-remark#1]
Recently, some large data files related to tests were committed to the repository.  For example:

- 12M: `similarity_join.548e4531baa98255-cgu.0.codegen.opt.yaml`
- 2.8M: `similarity_join.548e4531baa98255-cgu.0.opt.opt.yaml`

Presumably these files have been generated by some automated process.

The problem with committing large auto-generated files like this to the git history is that it grows the size of everyone's git clone of this project (forever).  A clean `git clone` of this young project is already 16M.  As these auto-generated files will likely need to be updated periodically, this will only grow if they are maintained in this way.

It would be better to commit the tooling to generate these files or to commit a script to fetch these files from another source.

Since the project and this git history are young, it may be worth fixing this problem quickly and retroactively by rewriting the history to exclude these and any other auto-generated data files and force-pushing over the default branch.

(Great idea for a project, by the way.  It looks like great work that will be helpful to the whole Rust ecosystem.)

**Comment by Kobzol** [comment]
Hi, that's a good point. However, I don't plan to update these files, they were generated manually once from a project, as I wanted to have tests using some real YAML files from an actual project.

I could have maybe manually trimmed these files to be smaller (or gzip them), but I guess that it's too late now, as I don't want to force push across a published version of the crate. And since I don't plan to update them in the future, I hope that it won't be such a problem.

**Comment by traviscross** [comment]
Good enough.  Just worth keeping in mind.  We all keep a lot of repositories around.  It adds up.  So it's worth trying to keep them as small as possible.  Best wishes on the success of this promising project.
