### ISSUE TITLE
Projects with paths containing spaces are split into multiple arguments due to missing quotes

### ISSUE THREAD

**Issue by wildbook** [Kobzol/cargo-remark#14]
The lack of quotes around `{}` in `-Zremark-dir={}` [here](https://github.com/Kobzol/cargo-remark/blob/9e1971ea93d28186de02edf1fec0cc0cafdcf3b8/src/cargo/mod.rs#L57) causes `cargo remark build` to break for any project in a path containing spaces, as the path is interpreted as multiple arguments.

Thank you for building an incredibly useful project on top of data I barely knew existed and would've probably never looked into otherwise!

**Comment by Kobzol** [comment]
Hi, thanks for the bug report! I poked into this and it seems that it might not be so trivial to resolve, since it's problematic to pass `RUSTFLAGS` containing values with spaces. I'll ask around on the [Cargo Zulip](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Passing.20Rustflags.20with.20spaces) to see if someone from the Cargo team can provide help.

**Comment by Kobzol** [comment]
Turns out that I was just doing something completely silly, it works now.

Could you please check if this version fixes the problem for you?
```bash
$ cargo install --git https://github.com/Kobzol/cargo-remark --branch fix-rustflags
```

**Comment by wildbook** [comment]
Hi, and I'm so sorry for the silence here. I only now got a notification due to the issue being closed, I didn't get any for the messages.

I've tried latest `main` now and I can confirm the fix works.

Thank you very much, and once again sorry!

**Comment by Kobzol** [comment]
No problem, thanks for testing it :)
